import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, test, vi } from "vitest";
import { api } from "../../shared/api/client";
import i18n from "../../shared/i18n";
import RunLifecycleDialog from "./RunLifecycleDialog";
vi.mock("../../shared/api/client", () => ({ api: { previewLifecycle: vi.fn(), trashRuns: vi.fn() } }));
beforeEach(async () => { vi.resetAllMocks(); await i18n.changeLanguage("en"); });
test("refreshes changed impact and requires an explicit second confirmation", async () => {
  const preview = { action: "trash" as const, affected_run_ids: ["full"], affected_runs: [], primary_replacements: {}, blocked_reasons: [] };
  vi.mocked(api.previewLifecycle).mockResolvedValueOnce(preview).mockResolvedValueOnce({ ...preview, affected_run_ids: ["full", "new-child"] });
  vi.mocked(api.trashRuns).mockRejectedValueOnce(new Error("Impact changed. Confirm again.")).mockResolvedValueOnce({ changed: 2, runs: [] });
  const onDone = vi.fn();
  render(<RunLifecycleDialog runIds={["full"]} action="trash" onClose={() => {}} onDone={onDone} />);
  const confirm = screen.getByRole("button", { name: "Confirm Trash" });
  expect(confirm).toBeDisabled();
  await waitFor(() => expect(confirm).toBeEnabled());
  fireEvent.click(confirm); fireEvent.click(confirm);
  await screen.findByText(/Impact changed/);
  await waitFor(() => expect(confirm).toBeEnabled());
  expect(api.trashRuns).toHaveBeenCalledTimes(1);
  expect(onDone).not.toHaveBeenCalled();
  fireEvent.click(confirm);
  await waitFor(() => expect(onDone).toHaveBeenCalledWith(2));
  expect(api.trashRuns).toHaveBeenLastCalledWith(["full"], {}, ["full", "new-child"]);
});
