import contextlib
import warnings

from .application.contracts import (
    AnalysisRequest,
    AnalysisResult,
    AnalystClaimType,
    AnalystReport,
    AuditedRangeEndpoint,
    CalculationRecord,
    ClaimImportance,
    DebateAgenda,
    DebateImportance,
    DebateIssue,
    DecisionBrief,
    DecisionCalculationUse,
    DecisionNumericAuditAppendix,
    EvidenceBundle,
    EvidenceItem,
    EvidenceTable,
    EvidenceTableCell,
    EvidenceTableColumn,
    EvidenceTableRow,
    EvidenceValueLocator,
    JudgeDraft,
    KeyClaim,
    MarketReferenceBasis,
    MarketReferenceLevel,
    MeasurementKind,
    NumericAuditAppendixStatus,
    NumericAuditComponentType,
    NumericAuditOmission,
    NumericAuditPhase,
    NumericAuditSnapshot,
    NumericAuditStatus,
    NumericCalculationStatus,
    NumericDisplayScale,
    NumericDisplayStatus,
    NumericRequirementCheck,
    NumericTemporalBasis,
    RebuttalReview,
    ReportAuditStatus,
    ReportLanguage,
    ReportSection,
    ResearchArtifact,
    ResearchCase,
    ResearchDecision,
    ResearchScenario,
    ResearchScenarioKind,
    ResearchWarning,
    RiskReview,
    RiskReviewAdjustment,
    RiskReviewDisposition,
    RunProfile,
    ScenarioReferenceCategory,
    ScenarioReferenceRange,
    StructuredRecoveryNotice,
    TableDataType,
    ValuationAssessment,
)
from .client import TradingAgents
from .version import __version__

__all__ = [
    "AnalysisRequest",
    "AnalysisResult",
    "AnalystClaimType",
    "AnalystReport",
    "CalculationRecord",
    "ClaimImportance",
    "DebateAgenda",
    "DebateImportance",
    "DebateIssue",
    "DecisionBrief",
    "DecisionCalculationUse",
    "DecisionNumericAuditAppendix",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceTable",
    "EvidenceTableCell",
    "EvidenceTableColumn",
    "EvidenceTableRow",
    "EvidenceValueLocator",
    "JudgeDraft",
    "KeyClaim",
    "MarketReferenceBasis",
    "MarketReferenceLevel",
    "MeasurementKind",
    "NumericAuditStatus",
    "NumericAuditAppendixStatus",
    "NumericAuditComponentType",
    "NumericCalculationStatus",
    "NumericDisplayScale",
    "NumericDisplayStatus",
    "NumericAuditOmission",
    "NumericAuditPhase",
    "NumericAuditSnapshot",
    "NumericRequirementCheck",
    "RebuttalReview",
    "ReportAuditStatus",
    "ReportLanguage",
    "ReportSection",
    "ResearchArtifact",
    "ResearchCase",
    "ResearchDecision",
    "ResearchScenario",
    "ResearchScenarioKind",
    "ResearchWarning",
    "RiskReview",
    "RiskReviewAdjustment",
    "RiskReviewDisposition",
    "RunProfile",
    "TableDataType",
    "TradingAgents",
    "ValuationAssessment",
    "AuditedRangeEndpoint",
    "NumericTemporalBasis",
    "ScenarioReferenceRange",
    "ScenarioReferenceCategory",
    "StructuredRecoveryNotice",
    "__version__",
]

# langchain-core 1.3.3 calls surface_langchain_deprecation_warnings() in
# its own __init__, which prepends default-action filters for its
# subclassed warning categories. To suppress a specific warning we must
# install our filter AFTER langchain-core has installed its own, so import
# it first. The package is a guaranteed transitive dep via langgraph.
with contextlib.suppress(ImportError):
    import langchain_core  # noqa: F401

# langgraph-checkpoint 4.0.3 calls Reviver() at module load without an
# explicit allowed_objects, which triggers a noisy pending-deprecation
# warning from langchain-core 1.3.3 on every interpreter start. The fix
# is already merged upstream (langchain-ai/langgraph#7743, 2026-05-08)
# and will arrive in the next langgraph-checkpoint release. Remove this
# block (and the langchain_core preload above) when we bump past it.
warnings.filterwarnings(
    "ignore",
    message=r"The default value of `allowed_objects`.*",
    category=PendingDeprecationWarning,
)
