const copy = {
  en: { connections: "Model connections", research: "Research defaults", data: "Data and news", storage: "Storage and maintenance", interface: "Interface", add: "Add connection", name: "Connection name", preset: "Service preset", edit: "Edit", enabled: "Enabled for new research", delete: "Delete connection", confirmDelete: "Delete this connection and its credentials? Retained reports remain readable, but failed Runs cannot retry with this connection.", back: "All connections", advanced: "Advanced connection settings", shared: "Use one connection", separate: "Choose connections separately", keep: "Choose the connection to keep", connection: "Connection", refresh: "Refresh models", manual: "Model ID (manual input supported)", unavailable: "Unavailable connection — choose a replacement", dirty: "Unsaved changes", leave: "Discard unsaved settings and leave?", latest: "Load latest values for comparison", reapply: "Keep my edits and use the latest revision", server: "Latest saved values", local: "Your edits", empty: "Add a service preset or a custom compatible endpoint.", missing: "Missing fields", protocol: "API interface", compatibility: "Model compatibility", required: "Require API key", news: "News and materials", sources: "Data sources", common: "Shared connection", quick: "Quick connection", deep: "Deep connection", choose: "Choose a connection", results: "Search results", response: "Use Responses API", disabled: "Disabled", ready: "Ready", credentials: "Credentials", resetHint: "Restore this connection's original template; credentials are preserved." },
  "zh-CN": { connections: "模型连接", research: "研究默认", data: "数据与新闻", storage: "存储与维护", interface: "界面偏好", add: "添加连接", name: "连接名称", preset: "服务预设", edit: "编辑", enabled: "允许新研究使用", delete: "删除连接", confirmDelete: "删除此连接及凭据？历史报告仍可查看，但失败任务将不能使用此连接重试。", back: "全部连接", advanced: "高级连接设置", shared: "共用连接", separate: "分别选择连接", keep: "选择要保留的连接", connection: "连接", refresh: "刷新模型列表", manual: "模型 ID（支持手动输入）", unavailable: "连接不可用，请选择替代连接", dirty: "有未保存的修改", leave: "放弃未保存的设置并离开？", latest: "读取最新值以比较", reapply: "保留我的修改并使用最新版本", server: "最新保存的值", local: "我的修改", empty: "添加常用服务预设，或自定义兼容接口。", missing: "缺少字段", protocol: "接口类型", compatibility: "模型兼容策略", required: "必须提供 API Key", news: "新闻与资料", sources: "数据来源", common: "共用连接", quick: "快速模型连接", deep: "深入模型连接", choose: "选择连接", results: "搜索结果", response: "使用 Responses API", disabled: "已停用", ready: "可用", credentials: "凭据", resetHint: "恢复此连接创建时的模板参数；保留凭据。" },
  ja: { connections: "モデル接続", research: "リサーチの既定値", data: "データとニュース", storage: "保存とメンテナンス", interface: "表示設定", add: "接続を追加", name: "接続名", preset: "サービスプリセット", edit: "編集", enabled: "新規リサーチで使用", delete: "接続を削除", confirmDelete: "接続と認証情報を削除しますか？過去のレポートは閲覧できますが、この接続で再試行できなくなります。", back: "すべての接続", advanced: "接続の詳細設定", shared: "接続を共用", separate: "接続を個別に選択", keep: "保持する接続を選択", connection: "接続", refresh: "モデルを更新", manual: "モデル ID（手動入力可）", unavailable: "利用できない接続です。別の接続を選択してください", dirty: "未保存の変更", leave: "未保存の設定を破棄して移動しますか？", latest: "最新の値と比較", reapply: "編集内容を保持して最新リビジョンを使用", server: "最新の保存値", local: "編集中の値", empty: "サービスプリセットまたは互換エンドポイントを追加してください。", missing: "不足項目", protocol: "API 形式", compatibility: "モデル互換性", required: "API キーを必須にする", news: "ニュースと資料", sources: "データソース", common: "共用接続", quick: "高速モデル接続", deep: "詳細モデル接続", choose: "接続を選択", results: "検索結果", response: "Responses API を使用", disabled: "無効", ready: "利用可能", credentials: "認証情報", resetHint: "作成時のテンプレートに戻します。認証情報は保持されます。" },
};
export function connectionCopy(language: string) {
  return copy[language.startsWith("zh") ? "zh-CN" : language.startsWith("ja") ? "ja" : "en"];
}

export function connectionField(language: string, key: string) {
  const labels: Record<string, [string, string, string]> = {
    api_key: ["API key", "API Key", "API キー"],
    base_url: ["API base URL", "API 服务地址", "API ベース URL"],
    deployment: ["Azure deployment (optional; otherwise use model ID)", "Azure 部署名（可选，留空使用模型 ID）", "Azure デプロイ名（省略時はモデル ID）"],
    api_version: ["Azure API version", "Azure API 版本", "Azure API バージョン"],
    region: ["AWS region", "AWS 区域", "AWS リージョン"],
    auth_mode: ["AWS authentication mode", "AWS 认证方式", "AWS 認証方式"],
    aws_profile: ["AWS profile (system authentication)", "AWS profile（系统认证模式）", "AWS プロファイル（システム認証）"],
  };
  return labels[key]?.[language.startsWith("zh") ? 1 : language.startsWith("ja") ? 2 : 0] ?? key;
}
